### ISSUE TITLE
Having issues with TypeError: guild.iconURL is not a function

### ISSUE THREAD

**Issue by MikeAlpine** [Androz2091/backups-bot#8]
TypeError: guild.iconURL is not a function

TypeError: guild.iconURL is not a function
    at /Users//Downloads/Eastide/node_modules/discord-backup/lib/index.js:147:44
    at step (/Users//Downloads/Eastide/node_modules/discord-backup/lib/index.js:33:23)

could there be another way to bypass this?

**Comment by Androz2091** [comment]
It is weird, because guild.iconURL should be a function.

**Comment by MikeAlpine** [comment]
nevermind i had to install Discord.js@latest my bad lol
